# Generated by Django 4.2.7 on 2023-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cashToCheckRatio', models.FloatField(default=0.4)),
                ('bu', models.IntegerField(default=0)),
            ],
        ),
    ]
